<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set primary_sequences CDATA #REQUIRED primary_count CDATA #REQUIRED primary_positions CDATA #REQUIRED
  control_sequences CDATA "" control_count CDATA "" control_positions CDATA "">
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_positions,
  seed,
  hsfrac,
  searchsize,
  maxsize,
  norand,
  csites,
  strands,
  brief,
  psp_file,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT searchsize (#PCDATA)*>
<!ELEMENT maxsize (#PCDATA)*>
<!ELEMENT norand (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT brief (#PCDATA)*>
<!ELEMENT psp_file (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED
		   order CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                llr CDATA #REQUIRED
                p_value CDATA #REQUIRED
                e_value CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="5.4.1" release="Sat Aug 21 19:23:23 2021 -0700">
<training_set primary_sequences="./motif_search/tmp_maxw_30/PP_0204_CysB.fasta" primary_count="17" primary_positions="10200" control_sequences="--none--" control_count="0" control_positions="0">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="Op145" length="600" weight="1.000000" />
<sequence id="sequence_1" name="Op1450" length="600" weight="1.000000" />
<sequence id="sequence_2" name="Op146" length="600" weight="1.000000" />
<sequence id="sequence_3" name="Op154" length="600" weight="1.000000" />
<sequence id="sequence_4" name="Op158" length="600" weight="1.000000" />
<sequence id="sequence_5" name="Op159" length="600" weight="1.000000" />
<sequence id="sequence_6" name="Op161" length="600" weight="1.000000" />
<sequence id="sequence_7" name="Op162" length="600" weight="1.000000" />
<sequence id="sequence_8" name="Op1799" length="600" weight="1.000000" />
<sequence id="sequence_9" name="Op1800" length="600" weight="1.000000" />
<sequence id="sequence_10" name="Op2285" length="600" weight="1.000000" />
<sequence id="sequence_11" name="Op3365" length="600" weight="1.000000" />
<sequence id="sequence_12" name="Op3366" length="600" weight="1.000000" />
<sequence id="sequence_13" name="Op3367" length="600" weight="1.000000" />
<sequence id="sequence_14" name="Op3368" length="600" weight="1.000000" />
<sequence id="sequence_15" name="Op3369" length="600" weight="1.000000" />
<sequence id="sequence_16" name="Op590" length="600" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.219</value>
<value letter_id="C">0.287</value>
<value letter_id="G">0.286</value>
<value letter_id="T">0.209</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme ./motif_search/tmp_maxw_30/PP_0204_CysB.fasta -oc ./motif_search/tmp_maxw_30/PP_0204_CysB -dna -mod zoops -p 8 -nmotifs 5 -evt 0.001 -minw 6 -maxw 30 -allw -minsites 5 </command_line>
<host>Hyungyus-MacBook-Pro.local</host>
<type>zoops</type>
<nmotifs>1000</nmotifs>
<evalue_threshold>0.001</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<spfun>E-value of product of p-values</spfun>
<min_width>6</min_width>
<max_width>30</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>5</minsites>
<maxsites>17</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_positions>10200</num_positions>
<seed>0</seed>
<hsfrac>0</hsfrac>
<searchsize>10200</searchsize>
<maxsize>0</maxsize>
<norand>no</norand>
<csites>1000</csites>
<strands>forward</strands>
<brief>1000</brief>
<psp_file></psp_file>
<priors_file></priors_file>
<reason_for_stopping>Stopped because the next motif E-value > 1.00e-03.</reason_for_stopping>
<background_frequencies source="--sequences--" order="0">
<alphabet_array>
<value letter_id="A">0.219</value>
<value letter_id="C">0.287</value>
<value letter_id="G">0.286</value>
<value letter_id="T">0.209</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="HWWAAHAWAWTRAWWWATAATATTTATATW" alt="MEME-1" width="30" sites="11" ic="27.1" re="32.0" llr="244" p_value="1.3e-055" e_value="3.5e-021" bayes_threshold="9.8928" elapsed_time="5.841185">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">105</value>
<value letter_id="C">-7</value>
<value letter_id="G">-1010</value>
<value letter_id="T">38</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">73</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">161</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">132</value>
<value letter_id="C">-165</value>
<value letter_id="G">-1010</value>
<value letter_id="T">80</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">205</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-120</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-165</value>
<value letter_id="G">-165</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">73</value>
<value letter_id="C">-66</value>
<value letter_id="G">-165</value>
<value letter_id="T">80</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">154</value>
<value letter_id="C">-7</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-120</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">73</value>
<value letter_id="C">-165</value>
<value letter_id="G">-1010</value>
<value letter_id="T">138</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-65</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">105</value>
<value letter_id="C">-66</value>
<value letter_id="G">-1010</value>
<value letter_id="T">80</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-66</value>
<value letter_id="G">-165</value>
<value letter_id="T">180</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">132</value>
<value letter_id="C">-165</value>
<value letter_id="G">35</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">173</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">38</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">132</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">112</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">132</value>
<value letter_id="C">-165</value>
<value letter_id="G">-1010</value>
<value letter_id="T">80</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">105</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">138</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">132</value>
<value letter_id="C">-165</value>
<value letter_id="G">-65</value>
<value letter_id="T">-20</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-127</value>
<value letter_id="C">-66</value>
<value letter_id="G">-65</value>
<value letter_id="T">138</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-65</value>
<value letter_id="T">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">173</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">38</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-27</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-165</value>
<value letter_id="T">180</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-165</value>
<value letter_id="G">-1010</value>
<value letter_id="T">-120</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-66</value>
<value letter_id="G">-1010</value>
<value letter_id="T">197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-27</value>
<value letter_id="C">-66</value>
<value letter_id="G">-1010</value>
<value letter_id="T">161</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-127</value>
<value letter_id="C">-66</value>
<value letter_id="G">-1010</value>
<value letter_id="T">180</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">154</value>
<value letter_id="C">-165</value>
<value letter_id="G">-1010</value>
<value letter_id="T">38</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-27</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-1010</value>
<value letter_id="T">197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">190</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-165</value>
<value letter_id="T">-120</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1010</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-165</value>
<value letter_id="T">212</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">32</value>
<value letter_id="C">-1010</value>
<value letter_id="G">-65</value>
<value letter_id="T">138</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.454545</value>
<value letter_id="C">0.272727</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.272727</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.363636</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.636364</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.545455</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.363636</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.909091</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.363636</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.363636</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.636364</value>
<value letter_id="C">0.272727</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.363636</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.545455</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.454545</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.363636</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.727273</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.545455</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.363636</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.727273</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.272727</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.545455</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.454545</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.545455</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.363636</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.454545</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.545455</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.545455</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.181818</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.090909</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.545455</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.727273</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.272727</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.181818</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.727273</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.818182</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.181818</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.636364</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.090909</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.727273</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.636364</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.272727</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.181818</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.818182</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.818182</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.090909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.090909</value>
<value letter_id="T">0.909091</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.272727</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.181818</value>
<value letter_id="T">0.545455</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[ACT][TA][AT]AA[AT][AC][TA]A[AT]T[AG][AT][AT][AT][TA]ATA[AT]TATTT[AT]TAT[TA]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_9" position="177" strand="plus" pvalue="2.12e-18" >
<left_flank>ATTTATATCT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CATTTTAGCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_8" position="391" strand="plus" pvalue="2.12e-18" >
<left_flank>ATTTATATCT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CATTTTAGCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_15" position="191" strand="plus" pvalue="1.18e-12" >
<left_flank>GGGATTATTC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>ACCATTTAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_6" position="406" strand="plus" pvalue="8.80e-12" >
<left_flank>TATTTTGGTT</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTTAATCGAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="242" strand="plus" pvalue="2.00e-11" >
<left_flank>GTCCGGTATA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>AACTAACTTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_13" position="166" strand="plus" pvalue="1.46e-10" >
<left_flank>TTCGTAAAGG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GCATAACAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_7" position="416" strand="plus" pvalue="2.30e-10" >
<left_flank>CGATAATGGA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>TATATGTAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_10" position="409" strand="plus" pvalue="2.48e-10" >
<left_flank>AAAATAACAA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GAAAGCCAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_5" position="153" strand="plus" pvalue="5.82e-10" >
<left_flank>GCTAAATGAT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>